import React, { useState } from "react";
import { appClient } from "@/api/appClient";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { 
  HelpCircle, Plus, Check, Trash2, Edit2, MessageCircle, 
  Calendar, Download, Share2, Loader2, CheckCircle, Clock
} from "lucide-react";
import { format } from "date-fns";
import { toast } from "sonner";

export default function DoctorQuestionsList({ userEmail }) {
  const queryClient = useQueryClient();
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [editingQuestion, setEditingQuestion] = useState(null);
  const [newQuestion, setNewQuestion] = useState("");
  const [newContext, setNewContext] = useState("");
  const [doctorNotes, setDoctorNotes] = useState("");

  const { data: questions = [], isLoading } = useQuery({
    queryKey: ['doctor-questions', userEmail],
    queryFn: () => appClient.entities.DoctorQuestion.filter(
      { user_email: userEmail },
      '-created_date'
    ),
    enabled: !!userEmail
  });

  const createMutation = useMutation({
    mutationFn: (data) => appClient.entities.DoctorQuestion.create({
      user_email: userEmail,
      question: data.question,
      context: data.context,
      status: "unanswered",
      source: "manual"
    }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['doctor-questions'] });
      setShowAddDialog(false);
      setNewQuestion("");
      setNewContext("");
      toast.success("Question saved! 📝");
    }
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }) => appClient.entities.DoctorQuestion.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['doctor-questions'] });
      setEditingQuestion(null);
      toast.success("Updated!");
    }
  });

  const deleteMutation = useMutation({
    mutationFn: (id) => appClient.entities.DoctorQuestion.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['doctor-questions'] });
      toast.success("Question removed");
    }
  });

  const markAsDiscussed = (question) => {
    updateMutation.mutate({
      id: question.id,
      data: {
        status: "discussed",
        discussed_date: format(new Date(), "yyyy-MM-dd"),
        doctor_notes: doctorNotes || undefined
      }
    });
    setDoctorNotes("");
  };

  const markAsResolved = (question) => {
    updateMutation.mutate({
      id: question.id,
      data: { status: "resolved" }
    });
  };

  const exportQuestions = () => {
    const unanswered = questions.filter(q => q.status === "unanswered");
    if (unanswered.length === 0) {
      toast.info("No unanswered questions to export");
      return;
    }

    let text = "📋 Questions for My Doctor\n";
    text += `Generated: ${format(new Date(), "MMMM d, yyyy")}\n\n`;
    
    unanswered.forEach((q, i) => {
      text += `${i + 1}. ${q.question}\n`;
      if (q.context) text += `   Context: ${q.context}\n`;
      text += `   Added: ${format(new Date(q.created_date), "MMM d, yyyy")}\n\n`;
    });

    text += "\n---\nGenerated by GlucoVital.fit";

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `doctor-questions-${format(new Date(), 'yyyy-MM-dd')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareViaWhatsApp = () => {
    const unanswered = questions.filter(q => q.status === "unanswered");
    if (unanswered.length === 0) {
      toast.info("No unanswered questions to share");
      return;
    }

    let text = "📋 *Questions for My Doctor*\n\n";
    unanswered.forEach((q, i) => {
      text += `${i + 1}. ${q.question}\n`;
    });
    text += "\n_Generated by GlucoVital.fit_";

    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
  };

  const unansweredQuestions = questions.filter(q => q.status === "unanswered");
  const discussedQuestions = questions.filter(q => q.status === "discussed");
  const resolvedQuestions = questions.filter(q => q.status === "resolved");

  return (
    <Card className="border-slate-100 shadow-sm">
      <CardHeader className="pb-4">
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2 text-lg">
            <HelpCircle className="w-5 h-5 text-violet-500" />
            Questions for Your Doctor
          </CardTitle>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={exportQuestions}>
              <Download className="w-4 h-4 mr-1" />
              Export
            </Button>
            <Button variant="outline" size="sm" onClick={shareViaWhatsApp}>
              <Share2 className="w-4 h-4 mr-1" />
              Share
            </Button>
            <Button size="sm" onClick={() => setShowAddDialog(true)} className="bg-violet-600 hover:bg-violet-700">
              <Plus className="w-4 h-4 mr-1" />
              Add
            </Button>
          </div>
        </div>
        <p className="text-sm text-slate-500 mt-1">
          Questions collected by Asha during your conversations. Review before your next visit.
        </p>
      </CardHeader>
      <CardContent className="space-y-6">
        {isLoading ? (
          <div className="flex justify-center py-8">
            <Loader2 className="w-6 h-6 animate-spin text-slate-400" />
          </div>
        ) : questions.length === 0 ? (
          <div className="text-center py-8 bg-slate-50 rounded-xl">
            <HelpCircle className="w-10 h-10 text-slate-300 mx-auto mb-2" />
            <p className="text-slate-500">No questions collected yet</p>
            <p className="text-xs text-slate-400 mt-1 max-w-xs mx-auto">
              Chat with Asha on WhatsApp — she'll ask if you have any questions for your doctor before your next visit
            </p>
          </div>
        ) : (
          <>
            {/* Unanswered */}
            {unansweredQuestions.length > 0 && (
              <div>
                <h4 className="font-medium text-slate-700 mb-3 flex items-center gap-2">
                  <Clock className="w-4 h-4 text-amber-500" />
                  To Discuss ({unansweredQuestions.length})
                </h4>
                <div className="space-y-2">
                  {unansweredQuestions.map(q => (
                    <QuestionCard 
                      key={q.id} 
                      question={q}
                      onMarkDiscussed={() => {
                        setEditingQuestion(q);
                      }}
                      onDelete={() => deleteMutation.mutate(q.id)}
                    />
                  ))}
                </div>
              </div>
            )}

            {/* Discussed */}
            {discussedQuestions.length > 0 && (
              <div>
                <h4 className="font-medium text-slate-700 mb-3 flex items-center gap-2">
                  <MessageCircle className="w-4 h-4 text-blue-500" />
                  Discussed ({discussedQuestions.length})
                </h4>
                <div className="space-y-2">
                  {discussedQuestions.map(q => (
                    <QuestionCard 
                      key={q.id} 
                      question={q}
                      onMarkResolved={() => markAsResolved(q)}
                      onDelete={() => deleteMutation.mutate(q.id)}
                      showNotes
                    />
                  ))}
                </div>
              </div>
            )}

            {/* Resolved */}
            {resolvedQuestions.length > 0 && (
              <div>
                <h4 className="font-medium text-slate-700 mb-3 flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-500" />
                  Resolved ({resolvedQuestions.length})
                </h4>
                <div className="space-y-2 opacity-60">
                  {resolvedQuestions.slice(0, 3).map(q => (
                    <QuestionCard 
                      key={q.id} 
                      question={q}
                      onDelete={() => deleteMutation.mutate(q.id)}
                      minimal
                    />
                  ))}
                  {resolvedQuestions.length > 3 && (
                    <p className="text-xs text-slate-400 text-center">
                      +{resolvedQuestions.length - 3} more resolved
                    </p>
                  )}
                </div>
              </div>
            )}
          </>
        )}
      </CardContent>

      {/* Add Question Dialog */}
      <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Add Question for Doctor</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium text-slate-700 mb-1.5 block">
                Your Question *
              </label>
              <Textarea
                value={newQuestion}
                onChange={(e) => setNewQuestion(e.target.value)}
                placeholder="e.g., Should I adjust my insulin dose if my morning sugars are consistently high?"
                className="h-24"
              />
            </div>
            <div>
              <label className="text-sm font-medium text-slate-700 mb-1.5 block">
                Context (optional)
              </label>
              <Input
                value={newContext}
                onChange={(e) => setNewContext(e.target.value)}
                placeholder="e.g., Morning readings have been 140-160 for the past week"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAddDialog(false)}>Cancel</Button>
            <Button 
              onClick={() => createMutation.mutate({ question: newQuestion, context: newContext })}
              disabled={!newQuestion.trim() || createMutation.isPending}
              className="bg-violet-600 hover:bg-violet-700"
            >
              {createMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : null}
              Save Question
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Mark as Discussed Dialog */}
      <Dialog open={!!editingQuestion} onOpenChange={() => setEditingQuestion(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Mark as Discussed</DialogTitle>
          </DialogHeader>
          <div className="py-4">
            <div className="bg-slate-50 p-3 rounded-lg mb-4">
              <p className="text-sm text-slate-700">{editingQuestion?.question}</p>
            </div>
            <label className="text-sm font-medium text-slate-700 mb-1.5 block">
              Doctor's Response / Notes (optional)
            </label>
            <Textarea
              value={doctorNotes}
              onChange={(e) => setDoctorNotes(e.target.value)}
              placeholder="What did your doctor say? Add notes here..."
              className="h-24"
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditingQuestion(null)}>Cancel</Button>
            <Button 
              onClick={() => markAsDiscussed(editingQuestion)}
              disabled={updateMutation.isPending}
              className="bg-blue-600 hover:bg-blue-700"
            >
              {updateMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : null}
              Mark as Discussed
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </Card>
  );
}

function QuestionCard({ question, onMarkDiscussed, onMarkResolved, onDelete, showNotes, minimal }) {
  const statusColors = {
    unanswered: "bg-amber-100 text-amber-700",
    discussed: "bg-blue-100 text-blue-700",
    resolved: "bg-green-100 text-green-700"
  };

  return (
    <div className={`p-3 rounded-lg border ${
      question.status === "unanswered" ? "bg-amber-50 border-amber-200" :
      question.status === "discussed" ? "bg-blue-50 border-blue-200" :
      "bg-slate-50 border-slate-200"
    }`}>
      <div className="flex items-start justify-between gap-3">
        <div className="flex-1">
          <p className="text-sm text-slate-800">{question.question}</p>
          {question.context && !minimal && (
            <p className="text-xs text-slate-500 mt-1">Context: {question.context}</p>
          )}
          {showNotes && question.doctor_notes && (
            <div className="mt-2 p-2 bg-white rounded border border-blue-100">
              <p className="text-xs text-blue-700">
                <strong>Doctor's response:</strong> {question.doctor_notes}
              </p>
            </div>
          )}
          <div className="flex items-center gap-2 mt-2">
            <Badge variant="outline" className={`text-xs ${statusColors[question.status]}`}>
              {question.status}
            </Badge>
            {question.source !== "manual" && (
              <Badge variant="outline" className="text-xs">
                via {question.source === "ai_chat" ? "AI" : "WhatsApp"}
              </Badge>
            )}
            <span className="text-xs text-slate-400">
              {format(new Date(question.created_date), "MMM d")}
            </span>
          </div>
        </div>
        {!minimal && (
          <div className="flex gap-1">
            {onMarkDiscussed && (
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={onMarkDiscussed}>
                <MessageCircle className="w-4 h-4 text-blue-500" />
              </Button>
            )}
            {onMarkResolved && (
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={onMarkResolved}>
                <Check className="w-4 h-4 text-green-500" />
              </Button>
            )}
            <Button variant="ghost" size="icon" className="h-8 w-8" onClick={onDelete}>
              <Trash2 className="w-4 h-4 text-red-400" />
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}