import React, { useState, useRef, useEffect } from "react";
import { appClient } from "@/api/appClient";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  FileText, Calendar, TrendingUp, TrendingDown, AlertTriangle, 
  CheckCircle, Lightbulb, Trophy, Share2, Download, Mail, X, Loader2, BarChart3, HelpCircle, Stethoscope 
} from "lucide-react";
import { toast } from "sonner";
import { SugarTrendChart, SugarDistributionChart, TimeOfDayChart, LogActivityChart, BPTrendChart } from "./ReportCharts";

export default function ReportViewer({ report, profile, onClose, onUpdate }) {
  const [sharing, setSharing] = useState(false);
  const [doctorEmail, setDoctorEmail] = useState(profile?.doctor_email || "");
  const [showShareDialog, setShowShareDialog] = useState(false);
  const [showExportOptions, setShowExportOptions] = useState(false);
  const [logs, setLogs] = useState([]);
  const [loadingLogs, setLoadingLogs] = useState(true);
  const reportRef = useRef(null);

  useEffect(() => {
    if (report?.user_email) {
      setLoadingLogs(true);
      // Fetch all logs and filter by user_email OR created_by (agent logs use created_by)
      appClient.entities.HealthLog.list('-created_date', 500)
        .then(allLogs => {
          const userLogs = allLogs.filter(log => 
            (log.user_email === report.user_email || log.created_by === report.user_email) &&
            log.status !== 'corrected' && log.status !== 'deleted'
          );
          const filtered = userLogs.filter(log => {
            const logDate = new Date(log.created_date);
            return logDate >= new Date(report.start_date) && logDate <= new Date(report.end_date);
          });
          setLogs(filtered);
        })
        .finally(() => setLoadingLogs(false));
    }
  }, [report]);

  const handleShare = async () => {
    if (!doctorEmail) {
      toast.error("Please enter doctor's email");
      return;
    }
    
    setSharing(true);
    try {
      await appClient.integrations.Core.SendEmail({
        to: doctorEmail,
        subject: `Health Report: ${profile?.name || 'Patient'} - ${format(new Date(report.start_date), "MMM d")} to ${format(new Date(report.end_date), "MMM d, yyyy")}`,
        body: `
Health Report for ${profile?.name || 'Patient'}
Period: ${format(new Date(report.start_date), "MMMM d")} - ${format(new Date(report.end_date), "MMMM d, yyyy")}
Type: ${report.report_type.charAt(0).toUpperCase() + report.report_type.slice(1)} Report

SUMMARY
${report.summary}

SUGAR STATISTICS
${report.sugar_stats ? `
• Average: ${report.sugar_stats.average} mg/dL
• Range: ${report.sugar_stats.lowest} - ${report.sugar_stats.highest} mg/dL
• Readings: ${report.sugar_stats.readings_count}
• In Target: ${report.sugar_stats.in_target_percent}%
` : 'No sugar data available'}

MEDICATION ADHERENCE
${report.medication_adherence}%

RISKS IDENTIFIED
${report.risks_identified?.map(r => `• ${r}`).join('\n') || 'None identified'}

RECOMMENDATIONS
${report.recommendations?.map(r => `• ${r}`).join('\n') || 'No recommendations'}

ACHIEVEMENTS
${report.achievements?.map(a => `• ${a}`).join('\n') || 'No achievements noted'}

QUESTIONS FOR DOCTOR
${report.questions_for_doctor?.map(q => `• ${q}`).join('\n') || 'No specific questions generated'}

---
Generated by GlucoVital.fit Health Buddy AI
        `
      });

      await appClient.entities.HealthReport.update(report.id, { 
        shared_with_doctor: true,
        doctor_email: doctorEmail
      });

      toast.success("Report shared with doctor!");
      setShowShareDialog(false);
      onUpdate?.();
    } catch (error) {
      toast.error("Failed to share report");
    } finally {
      setSharing(false);
    }
  };

  const handlePrint = (includeDoctorDetails = false) => {
    const printWindow = window.open('', '_blank');
    
    const doctorSection = includeDoctorDetails && (profile?.doctor_name || profile?.prescription_clinic) ? `
      <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
        <h2 style="color: #166534; margin-top: 0;">👨‍⚕️ Doctor & Clinic Details</h2>
        ${profile?.doctor_name ? `<p><strong>Doctor:</strong> ${profile.doctor_name}${profile?.doctor_specialization ? ` (${profile.doctor_specialization})` : ''}</p>` : ''}
        ${profile?.doctor_registration_no ? `<p><strong>Registration No:</strong> ${profile.doctor_registration_no}</p>` : ''}
        ${profile?.doctor_phone ? `<p><strong>Phone:</strong> ${profile.doctor_phone}</p>` : ''}
        ${profile?.doctor_whatsapp ? `<p><strong>WhatsApp:</strong> ${profile.doctor_whatsapp}</p>` : ''}
        ${profile?.prescription_clinic ? `<p><strong>Clinic:</strong> ${profile.prescription_clinic}</p>` : ''}
        ${profile?.prescription_clinic_address ? `<p><strong>Address:</strong> ${profile.prescription_clinic_address}</p>` : ''}
        ${profile?.prescription_clinic_phone ? `<p><strong>Clinic Phone:</strong> ${profile.prescription_clinic_phone}</p>` : ''}
        ${profile?.prescription_date ? `<p><strong>Last Prescription:</strong> ${format(new Date(profile.prescription_date), "MMMM d, yyyy")}</p>` : ''}
      </div>
    ` : '';

    printWindow.document.write(`
      <html>
        <head>
          <title>Health Report</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #1e293b; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
            h2 { color: #334155; margin-top: 24px; }
            .stat { background: #f1f5f9; padding: 16px; border-radius: 8px; margin: 8px 0; }
            .risk { color: #dc2626; }
            .achievement { color: #16a34a; }
            .recommendation { color: #2563eb; }
            ul { padding-left: 20px; }
            li { margin: 8px 0; }
          </style>
        </head>
        <body>
          <h1>🏥 Health Report</h1>
          <p><strong>Patient:</strong> ${profile?.name || 'Patient'}</p>
          <p><strong>Period:</strong> ${format(new Date(report.start_date), "MMMM d")} - ${format(new Date(report.end_date), "MMMM d, yyyy")}</p>
          <p><strong>Type:</strong> ${report.report_type.charAt(0).toUpperCase() + report.report_type.slice(1)}</p>
          
          ${doctorSection}
          
          <h2>📋 Summary</h2>
          <p>${report.summary}</p>
          
          ${report.sugar_stats ? `
          <h2>📊 Sugar Statistics</h2>
          <div class="stat">
            <p><strong>Average:</strong> ${report.sugar_stats.average} mg/dL</p>
            <p><strong>Range:</strong> ${report.sugar_stats.lowest} - ${report.sugar_stats.highest} mg/dL</p>
            <p><strong>Total Readings:</strong> ${report.sugar_stats.readings_count}</p>
            <p><strong>In Target Range:</strong> ${report.sugar_stats.in_target_percent}%</p>
          </div>
          ` : ''}
          
          <h2>💊 Medication Adherence</h2>
          <div class="stat"><strong>${report.medication_adherence}%</strong></div>
          
          ${report.risks_identified?.length > 0 ? `
          <h2 class="risk">⚠️ Risks Identified</h2>
          <ul>${report.risks_identified.map(r => `<li class="risk">${r}</li>`).join('')}</ul>
          ` : ''}
          
          ${report.recommendations?.length > 0 ? `
          <h2 class="recommendation">💡 Recommendations</h2>
          <ul>${report.recommendations.map(r => `<li class="recommendation">${r}</li>`).join('')}</ul>
          ` : ''}
          
          ${report.achievements?.length > 0 ? `
          <h2 class="achievement">🏆 Achievements</h2>
          <ul>${report.achievements.map(a => `<li class="achievement">${a}</li>`).join('')}</ul>
          ` : ''}
          
          ${report.questions_for_doctor?.length > 0 ? `
          <h2 style="color: #7c3aed;">❓ Questions for Your Doctor</h2>
          <p style="color: #6b7280; font-size: 12px; margin-bottom: 10px;">Based on your health data, consider asking these questions at your next visit:</p>
          <ul>${report.questions_for_doctor.map(q => `<li style="color: #5b21b6;">${q}</li>`).join('')}</ul>
          ` : ''}
          
          <hr style="margin-top: 40px;">
          <p style="color: #64748b; font-size: 12px;">Generated by GlucoVital.fit Health Buddy AI on ${format(new Date(), "MMMM d, yyyy")}</p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
    setShowExportOptions(false);
  };
  
  const hasDoctorDetails = profile?.doctor_name || profile?.prescription_clinic;

  if (!report) return null;

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto" ref={reportRef}>
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-slate-100 p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-50 rounded-lg">
              <FileText className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-800 capitalize">{report.report_type} Report</h2>
              <p className="text-xs text-slate-500 flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                {format(new Date(report.start_date), "MMM d")} - {format(new Date(report.end_date), "MMM d, yyyy")}
              </p>
            </div>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="w-5 h-5" />
          </Button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          <Tabs defaultValue="summary" className="w-full">
            <TabsList className="grid w-full grid-cols-2 mb-4 h-auto">
              <TabsTrigger value="summary" className="text-xs sm:text-sm py-2">Summary</TabsTrigger>
              <TabsTrigger value="charts" className="flex items-center gap-1 text-xs sm:text-sm py-2">
                <BarChart3 className="w-3 h-3 sm:w-4 sm:h-4" /> Charts
              </TabsTrigger>
            </TabsList>

            <TabsContent value="summary" className="space-y-6">
              {/* Summary */}
              <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-5 border border-blue-100">
                <h3 className="font-semibold text-slate-800 mb-2 flex items-center gap-2">
                  <TrendingUp className="w-4 h-4 text-blue-600" />
                  Summary
                </h3>
                <p className="text-slate-600 text-sm leading-relaxed">{report.summary}</p>
              </div>

              {/* Stats Grid */}
              {report.sugar_stats && (
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  <div className="bg-slate-50 rounded-xl p-4 text-center">
                    <p className="text-2xl font-bold text-slate-800">{report.sugar_stats.average}</p>
                    <p className="text-xs text-slate-500">Avg Sugar (mg/dL)</p>
                  </div>
                  <div className="bg-slate-50 rounded-xl p-4 text-center">
                    <p className="text-2xl font-bold text-slate-800">{report.sugar_stats.readings_count}</p>
                    <p className="text-xs text-slate-500">Readings</p>
                  </div>
                  <div className="bg-slate-50 rounded-xl p-4 text-center">
                    <p className="text-2xl font-bold text-green-600">{report.sugar_stats.in_target_percent}%</p>
                    <p className="text-xs text-slate-500">In Target</p>
                  </div>
                  <div className="bg-slate-50 rounded-xl p-4 text-center">
                    <p className="text-2xl font-bold text-slate-800">{report.medication_adherence}%</p>
                    <p className="text-xs text-slate-500">Med Adherence</p>
                  </div>
                </div>
              )}

          {/* Risks */}
          {report.risks_identified?.length > 0 && (
            <div>
              <h3 className="font-semibold text-slate-800 mb-3 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-500" />
                Risks Identified
              </h3>
              <div className="space-y-2">
                {report.risks_identified.map((risk, i) => (
                  <div key={i} className="flex items-start gap-2 bg-amber-50 rounded-lg p-3 border border-amber-100">
                    <TrendingDown className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-amber-800">{risk}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Recommendations */}
          {report.recommendations?.length > 0 && (
            <div>
              <h3 className="font-semibold text-slate-800 mb-3 flex items-center gap-2">
                <Lightbulb className="w-4 h-4 text-blue-500" />
                Recommendations
              </h3>
              <div className="space-y-2">
                {report.recommendations.map((rec, i) => (
                  <div key={i} className="flex items-start gap-2 bg-blue-50 rounded-lg p-3 border border-blue-100">
                    <CheckCircle className="w-4 h-4 text-blue-600 mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-blue-800">{rec}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Achievements */}
          {report.achievements?.length > 0 && (
            <div>
              <h3 className="font-semibold text-slate-800 mb-3 flex items-center gap-2">
                <Trophy className="w-4 h-4 text-amber-500" />
                Achievements
              </h3>
              <div className="space-y-2">
                {report.achievements.map((ach, i) => (
                  <div key={i} className="flex items-start gap-2 bg-green-50 rounded-lg p-3 border border-green-100">
                    <Trophy className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-green-800">{ach}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Questions for Doctor */}
          {report.questions_for_doctor?.length > 0 && (
            <div>
              <h3 className="font-semibold text-slate-800 mb-3 flex items-center gap-2">
                <Stethoscope className="w-4 h-4 text-violet-500" />
                Questions for Your Next Doctor Visit
              </h3>
              <div className="bg-violet-50 rounded-xl p-4 border border-violet-100">
                <p className="text-xs text-violet-600 mb-3">
                  💡 Based on your health data, here are questions you might want to ask your doctor:
                </p>
                <div className="space-y-2">
                  {report.questions_for_doctor.map((question, i) => (
                    <div key={i} className="flex items-start gap-2 bg-white rounded-lg p-3 border border-violet-100">
                      <HelpCircle className="w-4 h-4 text-violet-600 mt-0.5 flex-shrink-0" />
                      <p className="text-sm text-violet-800">{question}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
            </TabsContent>

            <TabsContent value="charts" className="space-y-4">
              {loadingLogs ? (
                <div className="text-center py-8 text-slate-400">Loading charts...</div>
              ) : (
                <>
                  <SugarTrendChart 
                    logs={logs} 
                    targetFasting={profile?.target_sugar_fasting || 100}
                    targetPostMeal={profile?.target_sugar_post_meal || 140}
                  />
                  <div className="grid md:grid-cols-2 gap-4">
                    <SugarDistributionChart logs={logs} targetPostMeal={profile?.target_sugar_post_meal || 140} />
                    <TimeOfDayChart logs={logs} />
                  </div>
                  <BPTrendChart logs={logs} />
                  <LogActivityChart logs={logs} startDate={report.start_date} endDate={report.end_date} />
                </>
              )}
            </TabsContent>
          </Tabs>
        </div>

        {/* Actions */}
        <div className="sticky bottom-0 bg-white border-t border-slate-100 p-4 flex gap-3">
          {hasDoctorDetails ? (
            <Button variant="outline" onClick={() => setShowExportOptions(true)} className="flex-1">
              <Download className="w-4 h-4 mr-2" />
              Export PDF
            </Button>
          ) : (
            <Button variant="outline" onClick={() => handlePrint(false)} className="flex-1">
              <Download className="w-4 h-4 mr-2" />
              Print / Save PDF
            </Button>
          )}
          <Button onClick={() => setShowShareDialog(true)} className="flex-1 bg-emerald-600 hover:bg-emerald-700">
            <Share2 className="w-4 h-4 mr-2" />
            Share with Doctor
          </Button>
        </div>
      </div>

      {/* Export Options Dialog */}
      <Dialog open={showExportOptions} onOpenChange={setShowExportOptions}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Export Report</DialogTitle>
          </DialogHeader>
          <div className="py-4 space-y-3">
            <p className="text-sm text-slate-600 mb-4">Choose what to include in your exported report:</p>
            <Button 
              variant="outline" 
              className="w-full justify-start h-auto py-4"
              onClick={() => handlePrint(true)}
            >
              <div className="flex items-start gap-3">
                <Stethoscope className="w-5 h-5 text-green-600 mt-0.5" />
                <div className="text-left">
                  <p className="font-medium">With Doctor & Clinic Details</p>
                  <p className="text-xs text-slate-500 mt-1">
                    Includes {profile?.doctor_name || 'doctor name'}, clinic info, and prescription details
                  </p>
                </div>
              </div>
            </Button>
            <Button 
              variant="outline" 
              className="w-full justify-start h-auto py-4"
              onClick={() => handlePrint(false)}
            >
              <div className="flex items-start gap-3">
                <FileText className="w-5 h-5 text-blue-600 mt-0.5" />
                <div className="text-left">
                  <p className="font-medium">Health Data Only</p>
                  <p className="text-xs text-slate-500 mt-1">
                    Export report without doctor or clinic information
                  </p>
                </div>
              </div>
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Share Dialog */}
      <Dialog open={showShareDialog} onOpenChange={setShowShareDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Share Report with Doctor</DialogTitle>
          </DialogHeader>
          <div className="py-4">
            <label className="text-sm font-medium text-slate-700 mb-1.5 block">Doctor's Email</label>
            <Input
              type="email"
              value={doctorEmail}
              onChange={(e) => setDoctorEmail(e.target.value)}
              placeholder="doctor@example.com"
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowShareDialog(false)}>Cancel</Button>
            <Button onClick={handleShare} disabled={sharing}>
              {sharing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Mail className="w-4 h-4 mr-2" />}
              Send Report
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}