import type {
  CareSetting,
  SpecialtyDefinition,
  SupportedLanguage,
} from "./types";

const CORE_CLINICAL = ["triage", "consultation", "documentation"] as const;
const HOSPITAL_EXTENDED = [
  "diagnostics",
  "care-coordination",
  "medication-safety",
  "discharge-and-followup",
  "abdm-compliance",
  "billing-and-coding",
] as const;

export const SPECIALTIES: SpecialtyDefinition[] = [
  {
    id: "family_medicine",
    labels: { en: "Family Medicine", hi: "पारिवारिक चिकित्सा" },
    category: "primary-care",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "care-coordination"],
  },
  {
    id: "internal_medicine",
    labels: { en: "Internal Medicine", hi: "आंतरिक चिकित्सा" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, ...HOSPITAL_EXTENDED],
  },
  {
    id: "pediatrics",
    labels: { en: "Pediatrics", hi: "शिशु रोग" },
    category: "women-and-child",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "medication-safety", "care-coordination"],
  },
  {
    id: "obstetrics_gynecology",
    labels: { en: "Obstetrics & Gynecology", hi: "स्त्री एवं प्रसूति रोग" },
    category: "women-and-child",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", "care-coordination"],
  },
  {
    id: "dermatology",
    labels: { en: "Dermatology", hi: "त्वचा रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "medication-safety"],
  },
  {
    id: "psychiatry",
    labels: { en: "Psychiatry", hi: "मनोचिकित्सा" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "care-coordination", "discharge-and-followup"],
  },
  {
    id: "orthopedics",
    labels: { en: "Orthopedics", hi: "अस्थि रोग" },
    category: "surgical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", ...HOSPITAL_EXTENDED],
  },
  {
    id: "ent",
    labels: { en: "ENT", hi: "कान, नाक, गला" },
    category: "surgical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning"],
  },
  {
    id: "ophthalmology",
    labels: { en: "Ophthalmology", hi: "नेत्र रोग" },
    category: "surgical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning"],
  },
  {
    id: "dental_oral_health",
    labels: { en: "Dental & Oral Health", hi: "दंत एवं मुख स्वास्थ्य" },
    category: "surgical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning"],
  },
  {
    id: "cardiology",
    labels: { en: "Cardiology", hi: "हृदय रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, ...HOSPITAL_EXTENDED],
  },
  {
    id: "neurology",
    labels: { en: "Neurology", hi: "तंत्रिका रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, ...HOSPITAL_EXTENDED],
  },
  {
    id: "nephrology",
    labels: { en: "Nephrology", hi: "गुर्दा रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, ...HOSPITAL_EXTENDED],
  },
  {
    id: "urology",
    labels: { en: "Urology", hi: "मूत्र रोग" },
    category: "surgical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", ...HOSPITAL_EXTENDED],
  },
  {
    id: "gastroenterology",
    labels: { en: "Gastroenterology", hi: "जठरांत्र रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "diagnostics", "care-coordination"],
  },
  {
    id: "endocrinology",
    labels: { en: "Endocrinology", hi: "अंतःस्रावी रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "medication-safety", "care-coordination"],
  },
  {
    id: "pulmonology",
    labels: { en: "Pulmonology", hi: "श्वसन रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "diagnostics", "discharge-and-followup"],
  },
  {
    id: "rheumatology",
    labels: { en: "Rheumatology", hi: "संधि रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "medication-safety"],
  },
  {
    id: "infectious_disease",
    labels: { en: "Infectious Disease", hi: "संक्रामक रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "diagnostics", "abdm-compliance"],
  },
  {
    id: "hematology",
    labels: { en: "Hematology", hi: "रक्त रोग" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "diagnostics", "medication-safety"],
  },
  {
    id: "medical_oncology",
    labels: { en: "Medical Oncology", hi: "मेडिकल ऑन्कोलॉजी" },
    category: "medical",
    settings: ["hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, ...HOSPITAL_EXTENDED],
  },
  {
    id: "radiation_oncology",
    labels: { en: "Radiation Oncology", hi: "रेडिएशन ऑन्कोलॉजी" },
    category: "medical",
    settings: ["hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", "care-coordination"],
  },
  {
    id: "surgical_oncology",
    labels: { en: "Surgical Oncology", hi: "सर्जिकल ऑन्कोलॉजी" },
    category: "surgical",
    settings: ["hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", ...HOSPITAL_EXTENDED],
  },
  {
    id: "general_surgery",
    labels: { en: "General Surgery", hi: "सामान्य शल्य चिकित्सा" },
    category: "surgical",
    settings: ["hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", ...HOSPITAL_EXTENDED],
  },
  {
    id: "neurosurgery",
    labels: { en: "Neurosurgery", hi: "न्यूरोसर्जरी" },
    category: "surgical",
    settings: ["hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", ...HOSPITAL_EXTENDED],
  },
  {
    id: "cardiothoracic_surgery",
    labels: { en: "Cardiothoracic Surgery", hi: "हृदय एवं वक्ष शल्य चिकित्सा" },
    category: "surgical",
    settings: ["hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", ...HOSPITAL_EXTENDED],
  },
  {
    id: "plastic_reconstructive_surgery",
    labels: { en: "Plastic & Reconstructive Surgery", hi: "प्लास्टिक एवं पुनर्निर्माण शल्य" },
    category: "surgical",
    settings: ["hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", "care-coordination"],
  },
  {
    id: "vascular_surgery",
    labels: { en: "Vascular Surgery", hi: "रक्तवाहिका शल्य चिकित्सा" },
    category: "surgical",
    settings: ["hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", ...HOSPITAL_EXTENDED],
  },
  {
    id: "anesthesiology",
    labels: { en: "Anesthesiology", hi: "निश्चेतना विज्ञान" },
    category: "supportive",
    settings: ["hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: ["procedure-planning", "documentation", "medication-safety", "care-coordination"],
  },
  {
    id: "emergency_medicine",
    labels: { en: "Emergency Medicine", hi: "आपातकालीन चिकित्सा" },
    category: "medical",
    settings: ["hospital"],
    deploymentPhase: "core",
    requiredCapabilities: ["triage", "consultation", "documentation", "diagnostics", "care-coordination", "abdm-compliance"],
  },
  {
    id: "critical_care",
    labels: { en: "Critical Care", hi: "गंभीर चिकित्सा" },
    category: "medical",
    settings: ["hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: ["consultation", "documentation", "diagnostics", "medication-safety", "care-coordination", "discharge-and-followup"],
  },
  {
    id: "radiology",
    labels: { en: "Radiology", hi: "रेडियोलॉजी" },
    category: "diagnostics",
    settings: ["hospital"],
    deploymentPhase: "core",
    requiredCapabilities: ["diagnostics", "documentation", "abdm-compliance", "billing-and-coding"],
  },
  {
    id: "pathology",
    labels: { en: "Pathology", hi: "रोग-विज्ञान" },
    category: "diagnostics",
    settings: ["hospital"],
    deploymentPhase: "core",
    requiredCapabilities: ["diagnostics", "documentation", "abdm-compliance", "billing-and-coding"],
  },
  {
    id: "nuclear_medicine",
    labels: { en: "Nuclear Medicine", hi: "न्यूक्लियर मेडिसिन" },
    category: "diagnostics",
    settings: ["hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: ["diagnostics", "documentation", "procedure-planning", "abdm-compliance"],
  },
  {
    id: "physical_medicine_rehabilitation",
    labels: { en: "PM&R", hi: "फिजिकल मेडिसिन और पुनर्वास" },
    category: "supportive",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "care-coordination", "discharge-and-followup"],
  },
  {
    id: "physiotherapy",
    labels: { en: "Physiotherapy", hi: "फिजियोथेरेपी" },
    category: "supportive",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: ["consultation", "documentation", "care-coordination", "discharge-and-followup"],
  },
  {
    id: "dietetics_nutrition",
    labels: { en: "Dietetics & Nutrition", hi: "आहार एवं पोषण" },
    category: "supportive",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: ["consultation", "documentation", "care-coordination", "medication-safety"],
  },
  {
    id: "pain_medicine",
    labels: { en: "Pain Medicine", hi: "दर्द चिकित्सा" },
    category: "supportive",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "medication-safety", "procedure-planning"],
  },
  {
    id: "geriatrics",
    labels: { en: "Geriatrics", hi: "वृद्ध चिकित्सा" },
    category: "medical",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "care-coordination", "discharge-and-followup"],
  },
  {
    id: "palliative_medicine",
    labels: { en: "Palliative Medicine", hi: "उपशामक चिकित्सा" },
    category: "supportive",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: [...CORE_CLINICAL, "care-coordination", "discharge-and-followup"],
  },
  {
    id: "neonatology",
    labels: { en: "Neonatology", hi: "नवजात शिशु चिकित्सा" },
    category: "women-and-child",
    settings: ["hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: ["consultation", "documentation", "medication-safety", "care-coordination", "discharge-and-followup"],
  },
  {
    id: "fertility_reproductive_medicine",
    labels: { en: "Fertility & Reproductive Medicine", hi: "प्रजनन एवं वंध्यत्व चिकित्सा" },
    category: "women-and-child",
    settings: ["clinic", "hospital"],
    deploymentPhase: "advanced",
    requiredCapabilities: [...CORE_CLINICAL, "procedure-planning", "care-coordination"],
  },
  {
    id: "community_medicine",
    labels: { en: "Community Medicine", hi: "समुदाय चिकित्सा" },
    category: "population-health",
    settings: ["clinic", "hospital"],
    deploymentPhase: "expanded",
    requiredCapabilities: ["triage", "consultation", "documentation", "care-coordination", "abdm-compliance"],
  },
  {
    id: "telemedicine",
    labels: { en: "Telemedicine", hi: "टेलीमेडिसिन" },
    category: "population-health",
    settings: ["clinic", "hospital"],
    deploymentPhase: "core",
    requiredCapabilities: [...CORE_CLINICAL, "abdm-compliance", "care-coordination"],
  },
];

export const SPECIALTY_BY_ID = new Map(
  SPECIALTIES.map((specialty) => [specialty.id, specialty]),
);

export function getSpecialtyById(id: string): SpecialtyDefinition | undefined {
  return SPECIALTY_BY_ID.get(id);
}

export function listSpecialtiesBySetting(setting: CareSetting): SpecialtyDefinition[] {
  return SPECIALTIES.filter((specialty) => specialty.settings.includes(setting));
}

export function getSpecialtyLabel(
  specialtyId: string,
  language: SupportedLanguage = "en",
): string | undefined {
  return SPECIALTY_BY_ID.get(specialtyId)?.labels[language];
}

export function listSpecialtyIds(): string[] {
  return SPECIALTIES.map((specialty) => specialty.id);
}
